name: quill_format
description: Simple and expressive format for describing rich-text content created for Quill.js editor.
version: 1.0.6
homepage: https://github.com/tony-soft/quill_format

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  collection: ^1.18.0
  quill_delta:
    git:
      url: https://github.com/tony-soft/quill-delta-dart.git
      ref: 682e3f664885e31d707d026363acbf7e52a0025e

dev_dependencies:
  test: ^1.25.2
  pedantic: ^1.11.1
